<?php 
// Information
define('EVENT_INFO_RSYNC_ENABLED',455);
define('EVENT_INFO_RSYNC_SCHEDULE_DISABLED',456);
define('EVENT_INFO_RSYNC_START',457);
define('EVENT_INFO_RSYNC_SUCCESS',458);
define('EVENT_INFO_RSYNC_CANCEL',459);
define('EVENT_INFO_RSYNC_STATUS',460);

// Error
define('EVENT_ERR_RSYNC_CONN_FAILED',667);
define('EVENT_ERR_RSYNC_SRC_NO_EXISTED',668);
define('EVENT_ERR_RSYNC_DEST_RO',669);
define('EVENT_ERR_RSYNC_NO_SPACE',670);
define('EVENT_ERR_RSYNC_IO',671);
define('EVENT_ERR_RSYNC_TIMEOUT',672);
define('EVENT_ERR_RSYNC_UNKNOWN',673);
define('EVENT_ERR_RSYNC_TASK_ERRCOUNT',674);
define('EVNET_ERR_RSYNC_SRC_RENAME',675);
define('EVENT_ERR_RSYNC_SRC_DELETED',676);
define('EVENT_ERR_RSYNC_DEST_NO_EXISTED',677);
define('EVENT_ERR_RSYNC_DEST_DENY',678);
define('EVENT_ERR_RSYNC_MAX_CONN',679);
define('EVENT_ERR_RSYNC_AUTH_FAILED',680);

//Warning
define('EVENT_WARN_RSYNC_TASK_RUNNING',514);
define('EVENT_WARN_RSYNC_RAID_MIGRATING',515);
define('EVENT_WARN_RSYNC_RAID_BUSY',516);

// Rsync test
define('EVENT_RSYNC_TEST_FAILED',700);
define('EVENT_RSYNC_TEST_AUTH_FAILED',701);
define('EVENT_RSYNC_TEST_CONN_TIMEOUT',702);
define('EVENT_RSYNC_TEST_DEST_NO_EXISTED',703);
define('EVENT_RSYNC_TEST_DENY',704);
define('EVENT_RSYNC_TEST_ADD_DEST_DIR_FAILED',705);
define('EVENT_RSYNC_TEST_IO_ERR',706);
define('EVENT_RSYNC_TEST_CONN_OK',707);
define('EVENT_RSYNC_TEST_NO_SPACE',708);
define('EVENT_RSYNC_TEST_MAX_CONN',709);
define('EVENT_RSYNC_TEST_UNKNOWN',710);
?>
