/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */

#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include <sys/time.h>
#include <signal.h>
#include <string.h>
#include <ctype.h>
#include "utility.h"
#include "cmd.h"
#include "cmd_queue.h"
#include "i2c.h"
#include "timer.h"
#include "menu.h"
uint8_t *_gpVersion="1600.1.7";
uint8_t _gPicVersion=0;
uint8_t _gCurrentState=STATE_INIT;
uint8_t _gTestMode=0;
uint8_t _gExitFlag=0;
uint8_t _gNewLANCheck=0;
#ifdef STATUS_LED
uint8_t _gStatusLEDFlag=0xff;
#endif
sigset_t _gSigMask;
static __sighandler_t _gQuitHandler=NULL;
static __sighandler_t _gKillHandler=NULL;
static __sighandler_t _gTermHandler=NULL;
static __sighandler_t _gIntHandler=NULL;

static void exit_handler(int32_t signum)
{
    IN(DEBUG_MODEL_MISC, "signum %d", signum);
    if(_gExitFlag)
        return;
    _gExitFlag=1;
    cmd_queue_release();
    menu_release();
    menu_queue_release();
    i2c_release();
    pipe_uninit();
#if(_DEBUG_ == 1 && _DEBUG_TO_FILE_ == 1)
    if(gDebugToFile == 1)
	util_debug_file_uninit();
#endif
    if(SIGQUIT == signum && _gQuitHandler)
        _gQuitHandler(signum);
    else if(SIGKILL == signum && _gKillHandler)
        _gKillHandler(signum);
    else if(SIGTERM == signum && _gTermHandler)
        _gTermHandler(signum);
    else if(SIGINT == signum && _gIntHandler)
    {
        debug_print(DEBUG_MODEL_MISC, "kekeke\n");
        _gIntHandler(signum);
    }
    exit(0);
}


int32_t main(int argc, char **argv)
{
    int32_t i = 0;
    pthread_t	vPollcmd;
    pthread_t	vPipecmd;

    _gCurrentState=STATE_INIT;

    for(i = 0; i < argc; i++)
    {
        if(0 == memcmp("-d", argv[i], 2))
        {
            if(i+1 < argc)
            {
                _gDebugFlagMask = strtol(argv[i+1], NULL, 0);
                i++;
            }
            else
            {
                _gDebugFlagMask=0xFF;
            }
            printf("enable debug, mask = 0x%04X\n", _gDebugFlagMask);
            _gDebugFlag=1;
        }
        else if(0 == memcmp("-t", argv[i], 2))
        {
            _gTestMode=1;
        }
    }

    _gQuitHandler = signal( SIGQUIT, exit_handler );
    _gKillHandler = signal( SIGKILL, exit_handler );
    _gTermHandler = signal( SIGTERM, exit_handler );
    _gTermHandler = signal( SIGINT, exit_handler );

#if(_DEBUG_ == 1 && _DEBUG_TO_FILE_ == 1)
    if(gDebugToFile == 1)
        util_debug_file_init();
#endif
    pipe_init();
    if(0 != i2c_init())
        return -1;
#ifdef STATUS_LED
    LED_init();
#endif	
#ifdef PUBLIC_GPIO
    GPIO_init();
#endif
    Flags_init();
    sysinfo_update_init();
    menu_init();
    signal( SIG_PROC_CMD, cmd_queue_handler );
    signal( SIG_PROC_MENU, menu_queue_handler );
    sigemptyset(&_gSigMask);
    
    pthread_create(&vPollcmd, NULL, timer_main, NULL);
    pthread_create(&vPipecmd, NULL, pipecmd, NULL);
    pthread_join( vPollcmd, NULL);
    pthread_join( vPipecmd, NULL);

    return (0);
}

